https-portal:
  image: steveltn/https-portal
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
  environment:
    - "DOMAINS=cftdi.ml -> http://web"

web:
  image: cesium/web
  ports:
    - "9000:5000"
    - "5000"
    - "80"
    - "443"
  links:
    - db
  volumes:
    - .:/home/cesium_app

db:
  image: postgres:9.5
  environment:
    - POSTGRES_USER=cesium
